### ISSUE TITLE
Issue With Crons

### ISSUE THREAD

**Issue by its-leofisher** [Sage-Goddess/odoo#43]
- Non-existent products are not created in Odoo
- why is it timing out? check non-sku, non-title logic
- resolve the expect a singleton error
- cancel status wasn't running

```
2022-04-20 16:26:38,498 0 ERROR sagegoddess-main-2586001 odoo.sh: Worker process (pid=37206) was killed by signal 9 (most likely hit a memory limit)
```

```
rAccount': None} 
2022-04-20 01:40:53,424 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Shipstation Warehouse : 22283 Shipstation Warehouse obj:shipstation.warehouse.detail(4,) 
2022-04-20 01:40:53,482 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Sale Order Created 2355514 
2022-04-20 01:40:53,940 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory: ======= Now adding order #2355514 to inventory queue. 
2022-04-20 01:40:53,940 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory: Attempting to store order details. 
2022-04-20 01:40:53,945 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:40:53,949 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:40:53,951 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:40:53,973 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Date Time Str 2022-04-19T18:31:00.0000000 Type : <class 'str'> 
2022-04-20 01:40:53,984 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg:  Advance Option >>>>>>>>>>>>>>>>>>>>>{'warehouseId': 22283, 'nonMachinable': False, 'saturdayDelivery': False, 'containsAlcohol': False, 'mergedOrSplit': False, 'mergedIds': [], 'parentId': None, 'storeId': 57490, 'customField1': 'wc_points_redemption_272377_2022_04_19_06_29', 'customField2': None, 'customField3': '', 'source': None, 'billToParty': None, 'billToAccount': None, 'billToPostalCode': None, 'billToCountryCode': None, 'billToMyOtherAccount': None} 
2022-04-20 01:40:53,984 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Shipstation Warehouse : 22283 Shipstation Warehouse obj:shipstation.warehouse.detail(4,) 
2022-04-20 01:40:54,023 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Sale Order Created 2355513 
2022-04-20 01:40:54,401 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory: ======= Now adding order #2355513 to inventory queue. 
2022-04-20 01:40:54,401 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory: Attempting to store order details. 
2022-04-20 01:40:54,404 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:40:54,405 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:40:54,407 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:40:55,934 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: 3 >>>>>>>>>> Getting an Issue in the  Imported  Process Expected singleton: product.product(79789, 79707, 79775) 
2022-04-20 01:40:55,938 13269 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Current Date >>>> 2022-04-20 02:40:55.938325 
2022-04-20 01:41:02,010 23645 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 01:41:02] "POST /longpolling/poll HTTP/1.0" 200 - 18 0.010 0.016
2022-04-20 01:41:06,133 27450 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/22306 (Backend Process) : Cou
```

```
2-04-20 01:27:41,959 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg:  Advance Option >>>>>>>>>>>>>>>>>>>>>{'warehouseId': 22283, 'nonMachinable': False, 'saturdayDelivery': False, 'containsAlcohol': False, 'mergedOrSplit': False, 'mergedIds': [], 'parentId': None, 'storeId': 57490, 'customField1': '', 'customField2': None, 'customField3': '', 'source': None, 'billToParty': None, 'billToAccount': None, 'billToPostalCode': None, 'billToCountryCode': None, 'billToMyOtherAccount': None} 
2022-04-20 01:27:41,960 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Shipstation Warehouse : 22283 Shipstation Warehouse obj:shipstation.warehouse.detail(4,) 
2022-04-20 01:27:42,037 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Sale Order Created 2355488 
2022-04-20 01:27:42,844 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory: ======= Now adding order #2355488 to inventory queue. 
2022-04-20 01:27:42,844 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory: Attempting to store order details. 
2022-04-20 01:27:42,847 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:27:42,849 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:27:42,850 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_inventory_items: Attempting to store item details from shipstation. 
2022-04-20 01:27:44,815 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: 3 >>>>>>>>>> Getting an Issue in the  Imported  Process Expected singleton: product.product(79789, 79707, 79775) 
2022-04-20 01:27:44,836 5296 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Current Date >>>> 2022-04-20 02:27:44.836354 
2022-04-20 01:27:45,487 5296 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 01:27:45] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.013 0.028
2022-04-20 01:27:53,084 5296 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 01:27:53] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.015 0.013
2022-04-20 01:27:55,916 5296 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 01:27:55] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.018 0.022
```

```
2022-04-13 07:57:09,977 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Data False 
2022-04-13 07:57:09,977 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Type GET 
2022-04-13 07:57:10,263 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: API Response >>>>>> <Response [200]> 
2022-04-13 07:57:10,660 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request URL https://ssapi.shipstation.com/orders?storeID=57490&orderNumber=2346546 
2022-04-13 07:57:10,661 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Data False 
2022-04-13 07:57:10,661 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Type GET 
2022-04-13 07:57:15,360 4 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [13/Apr/2022 07:57:15] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.008
2022-04-13 07:57:20,905 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: API Response >>>>>> <Response [200]> 
2022-04-13 07:57:21,558 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request URL https://ssapi.shipstation.com/orders?storeID=57490&orderNumber=2346544 
2022-04-13 07:57:21,558 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Data False 
2022-04-13 07:57:21,558 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Type GET 
2022-04-13 07:57:31,801 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: API Response >>>>>> <Response [200]> 
2022-04-13 07:57:32,060 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request URL https://ssapi.shipstation.com/orders?storeID=57490&orderNumber=2346545 
2022-04-13 07:57:32,060 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Data False 
2022-04-13 07:57:32,060 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Type GET 
2022-04-13 07:57:41,395 4 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [13/Apr/2022 07:57:41] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.007
2022-04-13 07:57:42,254 1810 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: API Response >>>>>> <Response [200]> 
2022-04-13 07:57:42,255 1810 ERROR sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Call from cron ShipStation: Send inventory data for server action #686 failed in Job #32 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_cron.py", line 139, in send_inventory_data_to_shipstation
    post_data_structure = self.env['shipstation.store.vts'].build_payload(records)
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_store_vts_sg.py", line 446, in build_payload
    copy_payload['orders'][0]['modifyDate'] = date_time.isoformat("T")  # 2022-01-04T11:53:54.2030000
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 110, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'IndexError'>: "list index out of range" while evaluating
'model.send_inventory_data_to_shipstation()'
2022-04-13 07:57:42,258 1810 INFO sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Job `ShipStation: Send inventory data` done. 
2022-04-13 07:57:42,260 1810 INFO sagegoddess-main-2586001 werkzeug: 10.0.15.146 - - [13/Apr/2022 07:57:42] "POST /xmlrpc/2/object HTTP/1.1" 200 - 671 8.385 55.474
2022-04-13 07:57:53,490 1810 INFO sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Starting job `Shipstation : Import Shipment`. 
2022-04-13 07:58:03,732 1810 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/06265 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-13 07:58:03,990 1810 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/06267 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-13 07:58:04,330 1810 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/06243 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-13 07:58:04,592 1810 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/06269 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-13 07:58:04,857 1810 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/06233 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-13 07:58:05,143 1810 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/06268 (Backend Pr
```

**Comment by its-leofisher** [comment]
Order # [2346545](https://ssapi.shipstation.com/orders?storeID=57490&orderNumber=2346545) seem to be the issue.  Setting it to complete made the process move along

**Comment by its-leofisher** [comment]
```

2022-04-20 14:23:46,716 23645 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [20/Apr/2022 14:23:46] "GET /web/content/45324-0d7b1c3/web_editor.assets_wysiwyg.js HTTP/1.0" 200 - 2 0.001 0.008
2022-04-20 14:23:51,031 27811 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [20/Apr/2022 14:23:51] "POST /web/dataset/call_kw/google.drive.config/get_google_drive_config HTTP/1.0" 200 - 6 0.004 0.008
2022-04-20 14:24:04,328 27811 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 14:24:04] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.007
2022-04-20 14:24:04,656 5296 ERROR sagegoddess-main-2586001 odoo.sql_db: bad query: UPDATE "stock_picking" SET "last_touched_at"='2022-04-20 14:23:44.275913',"ss_not_shipped_check_count"=89,"ss_overall_check_count"=89,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (22766)
ERROR: could not serialize access due to concurrent update
 
2022-04-20 14:24:04,657 5296 ERROR sagegoddess-main-2586001 odoo.sql_db: bad query: UPDATE "stock_picking" SET "write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (22766)
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2022-04-20 14:24:04,658 5296 ERROR sagegoddess-main-2586001 odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1398, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/user/community/printnode_base/controllers/main.py", line 86, in _call_kw
    result = super(DataSetProxy, self)._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 83, in method_direct_trigger
    cron.with_user(cron.user_id).with_context(lastcall=cron.lastcall).ir_actions_server_id.run()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: <class 'psycopg2.errors.InFailedSqlTransaction'>: "current transaction is aborted, commands ignored until end of transaction block
" while evaluating
'model.import_delivery_order_using_cron()'
2022-04-20 14:24:04,660 5296 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [20/Apr/2022 14:24:04] "POST /web/dataset/call_button HTTP/1.0" 200 - 177 0.096 56.937
2022-04-20 14:24:06,755 23645 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/21345 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-20 14:24:29,324 5296 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 14:24:29] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.010
2022-04-20 14:24:33,120 5296 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [20/Apr/2022 14:24:33] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.007
2022-04-20 14:24:35,875 5296 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [20/Apr/2022 14:24:35] "POST /longpolling/poll HTTP/1.0" 200 - 7 0.003 0.010
2022-04-20 14:24:36,689 5296 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [20/Apr/2022 14:24:36] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.007
2022-04-20 14:24:38,237 23645 INFO sagegoddess-main-2586001 odoo.addons.shipstation_shipping_odoo_integration.models.stock_picking_vts: SGHQ/OUT/21096 (Backend Process) : Could not transfer because there is a possibility of BackOrder. Please check delivery order. 
2022-04-20 14:24:55,329 5296 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.
```
