### ISSUE TITLE
SS Cron Updates

### ISSUE THREAD

**Issue by its-leofisher** [Sage-Goddess/odoo#52]
- Turn off skipped orders notifications
- turn off send inventory payload

```
2022-04-26 14:46:12,456 1500 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request URL https://ssapi.shipstation.com/orders?storeID=57490&orderNumber=2357989 
2022-04-26 14:46:12,457 1500 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Data False 
2022-04-26 14:46:12,457 1500 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Type GET 
2022-04-26 14:46:12,693 1500 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: API Response >>>>>> <Response [200]> 
2022-04-26 14:46:12,694 1500 ERROR sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Call from cron ShipStation: Send inventory data for server action #686 failed in Job #32 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_cron.py", line 139, in send_inventory_data_to_shipstation
    post_data_structure = self.env['shipstation.store.vts'].build_payload(records)
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_store_vts_sg.py", line 443, in build_payload
    copy_payload['orders'][0]['modifyDate'] = date_time.isoformat("T")  # 2022-01-04T11:53:54.2030000
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 110, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'IndexError'>: "list index out of range" while evaluating
'model.send_inventory_data_to_shipstation()'
2022-04-26 14:46:12,699 1500 INFO sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Job `ShipStation: Send inventory data` done. 
2022-04-26 14:46:12,701 1500 INFO sagegoddess-main-2586001 werkzeug: 10.0.1.74 - - [26/Apr/2022 14:46:12] "POST /xmlrpc/2/object HTTP/1.1" 200 - 190 1.672 3.575
2022-04-26 14:46:41,107 30 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [26/Apr/2022 14:46:41] "POST /longpolling/poll HTTP/1.0" 200 - 7 0.004 0.011
2022-04-26 14:46:51,398 30 INFO sagegoddess-main-2586001 werkzeug: 45.49.173.238 - - [26/Apr

```

**Comment by its-leofisher** [comment]
```
2022-04-26 18:20:03,577 11467 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: Request Type POST 
2022-04-26 18:20:05,134 30 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [26/Apr/2022 18:20:05] "POST /longpolling/poll HTTP/1.0" 200 - 7 0.003 0.008
2022-04-26 18:20:07,713 30 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [26/Apr/2022 18:20:07] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.008
2022-04-26 18:20:07,724 36 INFO sagegoddess-main-2586001 werkzeug: 104.152.233.68 - - [26/Apr/2022 18:20:07] "POST /longpolling/poll HTTP/1.0" 200 - 7 0.003 0.008
2022-04-26 18:20:08,172 11467 ERROR sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Call from cron Shipstation : Import Shipment for server action #511 failed in Job #24 
Traceback (most recent call last):
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_stock_picking_vts_sg.py", line 151, in import_delivery_order
    responses = response_result.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/api.py", line 793, in get
    return field_cache[record._ids[0]]
KeyError: 76679

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/fields.py", line 972, in __get__
    value = env.cache.get(record, self)
  File "/home/odoo/src/odoo/odoo/api.py", line 796, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'shipstation.operation.detail(76679,).company_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 110, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 632, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 501, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_stock_picking_vts_sg.py", line 65, in import_delivery_order_using_cron
    picking.sudo().import_delivery_order(operation_id)
  File "/home/odoo/src/user/custom/sg_shipstation_odoo_app/models/shipstation_stock_picking_vts_sg.py", line 312, in import_delivery_order
    shipstation_operation_details.sudo().create(
  File "<decorator-gen-230>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 326, in _model_create_single
    return create(self, arg)
  File "/home/odoo/src/user/community/shipstation_shipping_odoo_integration/models/shipstaion_operation_detail.py", line 67, in create
    company_id = operation and operation.company_id.id or self.env.user.company_id.id
  File "/home/odoo/src/odoo/odoo/fields.py", line 2485, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1002, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: shipstation.operation.detail(76679,), User: 1)
2022-04-26 18:20:08,175 11467 INFO sagegoddess-main-2586001 odoo.addons.base.models.ir_cron: Job `Shipstation : Import Shipment` done. 
2022-04-26 18:20:08,177 11467 INFO sagegoddess-main-2586001 werkzeug: 10.0.1.74 - - [26/Apr/2022 18:20:08] "POST /xmlrpc/2/object HTTP/1.1" 200 - 136 0.104 63.295
2022-04-26 18:20:08,626 11467 INFO sagegoddess-main-2586001 Shipstation: Import Order Response >>>>>> <Response [200]> 
2022-04-26 18:20:08,628 11467 INFO sagegoddess-main-2586001 Shipstation: Import Order Request Data https://ssapi.shipstation.com/orders?modifyDateStart=2022-04-25T22:19:57.0000000&modifyDateEnd=2022-04-26T20:19:57.0000000&storeId=57490&orderStatus=cancelled&pageSize=500&sortBy=ModifyDate&sortDir=DESC&page=1 
2022-04-26 18:20:09,126 11467 INFO sagegoddess-main-2586001 Shipstation: Import Order Response >>>>>> <Response [200]> 
2022-04-26 18:20:09,128 11467 INFO sagegoddess-main-2586001 odoo.addons.sg_shipstation_odoo_app.models.shipstation_store_vts_sg: >>> Amount of orders processing: 26 
2022-04-26 18:20:09,184 30 INFO sagegoddess-main-2586001 werkzeug: 35.129.82.113 - - [26/Apr/2022 18:20:09] "POST /longpolling/im_status HTTP/1.0" 200 - 4 0.003 0.008
```

**Comment by its-leofisher** [comment]
Two different products, no sku, same title and in Same Order constantly has qty updated
2361326 - https://sagegoddess.odoo.com/web#id=31385&action=292&model=sale.order&view_type=form&cids=1&menu_id=176

Shipstation is awaiting shipment, has both products without sku same name
